---
title: "Autochamber_DataViz_2024"
author: "Stephanie J. Wilson"
date: "2026-02-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(purrr)
library(stringr)
library(lubridate)
```

## Read in Data
```{r, echo=FALSE}

##CO2
# List processed CO2 files
CO2.files <- list.files(
  path = "Processed_Data",
  pattern = "CO2",
  full.names = TRUE,
  recursive = TRUE
)

#read in data & add a plot column to each 
CO2_dat <- map(CO2.files, read.csv)|>list_rbind()
CO2_event <- CO2_dat %>% 
  rename(FCO2.LIN = lin_flux.estimate, 
         FCO2.LIN_R2 = lin_r.squared, 
         unique_ID = Plot) %>% 
  filter(TIMESTAMP >= "2026-06-07 00:00:00") %>% 
  select(unique_ID, FCO2.LIN, FCO2.LIN_R2)


##CH4
# List processed CH4 files
CH4.files <- list.files(
  path = "Processed_Data",
  pattern = "CH4",
  full.names = TRUE,
  recursive = TRUE
)

#read in data & add a plot column to each 
CH4_dat <- map(CH4.files, read.csv)|>list_rbind()
CH4_event <- CH4_dat %>% 
  rename(FCH4.LIN = lin_flux.estimate, 
         FCH4.LIN_R2 = lin_r.squared, 
         unique_ID = Plot) %>% 
  filter(TIMESTAMP >= "2026-06-07 00:00:00") %>% 
  select(unique_ID, FCH4.LIN, FCH4.LIN_R2)


##N2O
# List processed N2O files
N2O.files <- list.files(
  path = "Processed_Data",
  pattern = "N2O",
  full.names = TRUE,
  recursive = TRUE
)

#read in data & add a plot column to each 
N2O_dat <- map(N2O.files, read.csv)|>list_rbind()
N2O_event <- N2O_dat %>% 
  rename(FN2O.LIN = lin_flux.estimate, 
         FN2O.LIN_R2 = lin_r.squared, 
         unique_ID = Plot) %>% 
  filter(TIMESTAMP >= "2026-06-07 00:00:00") %>% 
  select(unique_ID, FN2O.LIN, FN2O.LIN_R2)


# Put your data frames into a list and reduce them with left_join
# Extract Collar number and Plot
dat <- list(CO2_event, CH4_event, N2O_event) %>% 
  reduce(left_join, by = "unique_ID") %>% 
  mutate(datetime = ymd_hms(str_remove(unique_ID, "^Collar_\\d+_"))) %>% 
  mutate(Collar = str_extract(unique_ID, "^Collar_\\d+")) %>% 
  mutate(Collar = str_remove(Collar, "Collar_")) %>% 
  mutate(Plot = case_when(
    Collar == "13" | Collar == "14" | Collar == "15" | Collar == "16" | Collar == "49" ~ "Control", 
    Collar == "41" | Collar == "42" | Collar == "43" | Collar == "44" | Collar == "40" | Collar == "38" | Collar == "45" ~ "Freshwater", 
    Collar == "29" | Collar == "30" | Collar == "31" | Collar == "32" | Collar == "50" | Collar == "51" | Collar == "52" ~ "Saltwater", 
  ))

```

## Box Plots across Plots 
```{r pressure, echo=FALSE}

#7810
co2b <- ggplot()+
  geom_boxplot(data=dat, aes(x=Plot, y=FCO2.LIN, fill=Plot)) + 
  theme_classic() + 
  labs(title= "7810 CO2 Flux", x=" ", y= expression(paste("CO2 Flux (umol m-2 s-1)"))) +
  scale_fill_manual(values=c('springgreen2', 'cyan2', 'violetred2')) 
  # ylim(-30,30) +
  # theme(panel.background = element_rect(colour = "black", linewidth  =1.2), 
  #       legend.position = "NONE", 
  #       legend.title= element_blank(), 
  #       axis.text=element_text(size=12), 
  #       axis.title=element_text(size=12), 
  #       strip.text.x = element_text(size = 12)) 
co2b

ch4b <- ggplot()+
  geom_boxplot(data=dat, aes(x=Plot, y=FCH4.LIN, fill=Plot)) + 
  theme_classic() + 
  labs(title= "7810 CH4 Flux", x=" ", y= expression(paste("CH4 Flux (nmol m-2 s-1)"))) +
  scale_fill_manual(values=c('springgreen2', 'cyan2', 'violetred2'))
  # ylim(-20,20)+
  # theme(panel.background = element_rect(colour = "black", linewidth  =1.2), 
  #       legend.position = "NONE", 
  #       legend.title= element_blank(), 
  #       axis.text=element_text(size=12), 
  #       axis.title=element_text(size=12), 
  #       strip.text.x = element_text(size = 12)) 
ch4b

```


## Including Plots
```{r pressure, echo=FALSE}
dat$FCO2.LIN_R2 <- as.numeric(dat$FCO2.LIN_R2 )

dat_mod <- filter(dat, FCO2.LIN_R2 > -100)

co2br <- ggplot(dat_mod, aes(datetime, FCO2.LIN, color = FCO2.LIN_R2)) + 
  facet_wrap(~Plot, ncol = 3) + 
  geom_point(size=2) + theme_classic()+
  # ylim(-30,30)+
  ylab("CO2 flux (µmol/m2/s)")
co2br


dat_mod$FCH4.LIN_R2 <- as.numeric(dat_mod$FCH4.LIN_R2 )
dat_mod <- filter(dat_mod, FCH4.LIN_R2 > -100)
ch4br <- ggplot(dat_mod, aes(datetime, FCH4.LIN, color = FCH4.LIN_R2)) + 
  facet_wrap(~Plot, ncol = 3) + 
  labs(title= "7810 CH4 Flux", x=" ", y= expression(paste("CH4 Flux (nmol m-2 s-1)"))) +
  geom_point(size=2) + theme_classic()
  # ylim(-30,30)
ch4br

```


## Plot by Port Label (ie., by the collar)
```{r pressure, echo=FALSE}

#make color = port label 
co2br <- ggplot(dat_mod, aes(datetime, FCO2.LIN, color = Collar)) + 
  facet_wrap(~Plot, nrow = 3, scales = "free") + 
  geom_point(size=2) + theme_classic()+
  geom_hline(yintercept = 0) + 
  labs(title= "7810 Auto Chamber Data", x=" ") +
  ylab(expression(paste( CO [2], " Flux (μmol m"^-2* " s"^-1*")"))) +
  theme(legend.title = element_blank()) + 
  theme(axis.title.x = element_text(size=12), axis.text = element_text(size=10),
        axis.title.y = element_text(size=12), legend.text=element_text(size=10),
        panel.border = element_rect(colour = "black", fill=NA, linewidth =1), 
        strip.text = element_text( size = 12)) +
  scale_x_datetime(
    date_breaks = "12 hours",      # Sets the interval for the breaks
    date_labels = "%b %d %H:%M"         # Formats the timestamp display
  )
co2br

ch4br <- ggplot(dat_mod, aes(datetime, FCH4.LIN, color = Collar)) + 
  facet_wrap(~Plot, nrow = 3, scales = "free") + 
  geom_point(size=2) + theme_classic()+
  labs(title= "7810 Auto Chamber Data", x=" ") +
  ylab(expression(paste( CH [4], " Flux (nmol m"^-2* " s"^-1*")"))) +
  theme(legend.title = element_blank()) + 
  theme(axis.title.x = element_text(size=12), axis.text = element_text(size=10),
        axis.title.y = element_text(size=12), legend.text=element_text(size=10),
        panel.border = element_rect(colour = "black", fill=NA, linewidth =1), 
        strip.text = element_text( size = 12)) +
  scale_x_datetime(
    date_breaks = "12 hours",      # Sets the interval for the breaks
    date_labels = "%b %d %H:%M"         # Formats the timestamp display
  )
ch4br
```

## Plot by Port Label (ie., by the collar)
```{#r pressure, echo=FALSE}

dat_mod <- dat_mod %>% 
  filter(!Collar == "NA")

#make color = port label 
co2br <- ggplot(dat_mod, aes(datetime, FCO2.LIN, color = Collar)) + 
  facet_wrap(~Plot, ncol = 3) + 
  geom_boxplot(size=2) + theme_classic()+
  #geom_hline(yintercept = 0) + 
  labs(title= "7810 Auto Chamber Data", x=" ") +
  ylab(expression(paste( CO [2], " Flux (μmol m"^-2* " s"^-1*")"))) +
  # ylim(-5,20)+
  theme(legend.title = element_blank()) + 
  theme(axis.title.x = element_text(size=12), axis.text = element_text(size=12),
        axis.title.y = element_text(size=12), legend.text=element_text(size=10),
        panel.border = element_rect(colour = "black", fill=NA, linewidth =1), 
        strip.text = element_text( size = 12))
co2br

ch4br <- ggplot(dat_mod, aes(datetime, FCH4.LIN, color=Collar)) + 
  facet_wrap(~Plot, ncol = 3) + 
  geom_boxplot(size=2) + theme_classic()+
  # ylim(-20,10)+
  labs(title= "7810 Auto Chamber Data", x=" ") +
  ylab(expression(paste( CH [4], " Flux (nmol m"^-2* " s"^-1*")"))) +
  theme(legend.title = element_blank()) + 
  theme(axis.title.x = element_text(size=12), axis.text = element_text(size=12),
        axis.title.y = element_text(size=12), legend.text=element_text(size=10),
        panel.border = element_rect(colour = "black", fill=NA, linewidth =1), 
        strip.text = element_text( size = 12)) + 
  geom_text(aes(label = Collar),
            vjust = -0.5)
ch4br


```


## Including Plots

```{r pressure, echo=FALSE}

```

